/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  codingSidebar: [
    {
      type: "category",
      label: "C and C++",
      link: {
        type: "doc",
        id: "coding/c_cpp/intro"
      },
      collapsed: true,
      items: [
        "coding/c_cpp/second",
        "coding/c_cpp/third"
      ]
    },
    {
      type: "category",
      label: "Python",
      link: {
        type: "doc",
        id: "coding/python/intro"
      },
      collapsed: false,
      items: [
        "coding/python/second"
      ]
    },

  ],

  linuxSidebar: [{ type: 'autogenerated', dirName: 'linux' }],

  yoctoSidebar: [{ type: 'autogenerated', dirName: 'yocto' }],
};

export default sidebars;
