/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

    codingSidebar: [
        {
            type: "category",
            label: "C/C++ Hub",
            link: {
                type: "doc",
                id: "coding/c_cpp/welcome-c-cpp"
            },
            collapsed: false,
            items: [
                "coding/c_cpp/styling-guidelines-c-cpp",
            ]
        },
        {
            type: "category",
            label: "Python Hub",
            link: {
                type: "doc",
                id: "coding/python/welcome-python"
            },
            collapsed: false,
            items: [
                "coding/python/styling-guidelines-python",
                "coding/python/how-to-create-a-python-module"
            ]
        },
        {
            type: "category",
            label: "Miscellaneous Hub",
            collapsed: false,
            items: [
                "coding/misc/using-editorconfig",
            ]
        }
    ],

    linuxSidebar: [{ type: 'autogenerated', dirName: 'linux' }],

    yoctoSidebar: [{ type: 'autogenerated', dirName: 'yocto' }],
};

export default sidebars;
